spring:
  application:
    name: Omni-BE-Gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${HTTPS_GATEWAY_URL}
              - ${HTTPS_FRONT_URL}
              - ${FRONT_URL}
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            exposedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - PUT
              - GET
              - POST
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: user-service
          uri: ${USER_SERVER_ADDRESS}
          predicates:
            - Path=/user/**

        - id: sponsor-service
          uri: ${SPONSOR_SERVER_ADDRESS}
          predicates:
            - Path=/sponsor/**

        - id: payment-service
          uri: ${PAYMENT_SERVER_ADDRESS}
          predicates:
            - Path=/payment/**

        - id: card-service
          uri: ${CARD_SERVER_ADDRESS}
          predicates:
            - Path=/card/**

        - id: ai-swagger-api-docs
          uri: ${AI_SERVER_ADDRESS}
          predicates:
            - Path=/flask/**

  jwt:
    secret: ${JWT_SECRET_KEY}


springdoc:
  swagger-ui:
    urls[0]:
      name: Omni-BE-User
      url: ${HTTPS_GATEWAY_URL}/user/v3/api-docs
    urls[1]:
      name: Omni-BE-Sponsor
      url: ${HTTPS_GATEWAY_URL}/sponsor/v3/api-docs
    urls[2]:
      name: Omni-BE-Payment
      url: ${HTTPS_GATEWAY_URL}/payment/v3/api-docs
    urls[3]:
      name: Omni-BE-Card
      url: ${HTTPS_GATEWAY_URL}/card/v3/api-docs
    urls[4]:
      name: Omni-BE-File
      url: ${HTTPS_GATEWAY_URL}/file/v3/api-docs
    urls[5]:
      name: Omni-BE-AI
      url: ${HTTPS_GATEWAY_URL}/flask/v3/api-docs