spring:
  application:
    name: Omni-BE-Gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${HTTPS_GATEWAY_URL}
              - ${HTTPS_FRONT_URL}
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            exposedHeaders:
              - x-requested-with
              - Authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: user-swagger-api-docs
          uri: ${USER_SERVER_ADDRESS}
          predicates:
            - Path=/omni-be-user/v3/api-docs

        - id: sponsor-swagger-api-docs
          uri: ${SPONSOR_SERVER_ADDRESS}
          predicates:
            - Path=/omni-be-sponsor/v3/api-docs

        - id: payment-swagger-api-docs
          uri: ${PAYMENT_SERVER_ADDRESS}
          predicates:
            - Path=/omni-be-payment/v3/api-docs

        - id: card-swagger-api-docs
          uri: ${CARD_SERVER_ADDRESS}
          predicates:
            - Path=/omni-be-card/v3/api-docs

        - id: file-swagger-api-docs
          uri: ${FILE_SERVER_ADDRESS}
          predicates:
            - Path=/omni-be-file/v3/api-docs

#        - id: ai-swagger-api-docs
#          uri: ${AI_SERVER_ADDRESS}
#          predicates:
#            - Path=/omni-be-ai/v3/api-docs

springdoc:
  swagger-ui:
    urls[0]:
      name: Omni-BE-User
      url: https://${HTTPS_GATEWAY_URL}/omni-be-user/v3/api-docs
    urls[1]:
      name: Omni-BE-Sponsor
      url: https://${HTTPS_GATEWAY_URL}/omni-be-sponsor/v3/api-docs
    urls[2]:
      name: Omni-BE-Payment
      url: https://${HTTPS_GATEWAY_URL}/omni-be-payment/v3/api-docs
    urls[3]:
      name: Omni-BE-Card
      url: https://${HTTPS_GATEWAY_URL}/omni-be-card/v3/api-docs
    urls[4]:
      name: Omni-BE-File
      url: https://${HTTPS_GATEWAY_URL}/omni-be-file/v3/api-docs
#    urls[5]:
#      name: Omni-BE-AI
#      url: